[package]
name = "rust-test-gerkin"
version = "0.1.0"
authors = ["Swann <swann@devloup.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
name = "fizz_buzz_lib"
path = "src/lib.rs"

[dependencies]
